# Add User Mutation
POST http://localhost:4000/graphql
Content-Type: application/json

{
  "query": "mutation($username: String!, $password: String!, $role: String!) { addUser(username: $username, password: $password, role: $role) { id username role } }",
  "variables": {
    "username": "testdude2",
    "password": "admin123",
    "role": "teacher"
  }
}

###
# Login Mutation
POST http://localhost:4000/graphql
Content-Type: application/json

{
  "query": "mutation Login($username: String!, $password: String!) { login(username: $username, password: $password) { value } }",
  "variables": {
    "username": "testdude2",
    "password": "admin123"
  }
}

###
# Authenticated Query
POST http://localhost:4000/graphql
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RkdWRlMiIsImlkIjoiNjY5NzRmZDdlMzZiOTQxMmVlY2I4OTE1IiwiaWF0IjoxNzIxMTk2MTE1fQ.l6g5Efg7XxHyLR4D5WBty5HvSlDtg7KSgfKOMnZCpr8

{
  "query": "query Me { me { id username role } }"
}
